# AIM: Handling Missing Values

**Name : Trideep Nandi**

**Class : CS4**

**Batch: 2**

**Enrollment : 0827CS211248**

Practice Task1:
To explore and study UCI and kaggle data repository.

Observations:
*   The repositories contained various types of datasets related to a specific problem.
*   Datasets are available mostly in csv(comma separated values) type format.
*   Based on user's preference , the side bar allows the user to filter the datasets and select the dataset which will be suitable.
*   vast variety of datasets are available like numerical, mixed, categorical.
*   Datasets associated with various platforms like engineering, chemical, entertainment, social media etc which will again be beneficial for users training their model for  specific domain.

Practice Test2:
Download and explore dataset.

In [1]:
import pandas as pd

Pandas read_csv() function imports a CSV (comma separated values) file to DataFrame format

In [3]:
df= pd.read_csv('content/ElectronicsData.csv')

The df.shape in pandas returns a tuple representing the dimensionality of the DataFrame. It gives the number of rows and columns in the DataFrame, with the format (rows, columns).

In [4]:
df.shape

(643, 7)

The head() method returns a specified number of rows, string from the top. The df.head(7) in pandas returns the first 7 rows of the DataFrame df.

In [5]:
df.head(7)

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
0,Batteries,$20.99,No Discount,NaN,"Duracell Coppertop Alkaline AA Batteries, 40-c...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
1,Batteries,$20.99,No Discount,NaN,"Duracell Coppertop Alkaline AAA Batteries, 40-...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
2,Batteries,$20.99,No Discount,NaN,"Duracell 9V Alkaline Batteries, 8-count",$,Long-Lasting Batteries Designed for Dependabil...
3,Batteries,$18.99,No Discount,NaN,"Duracell C Alkaline Batteries, 14-count",$,Long-Lasting Batteries Designed for Dependabil...
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
5,Batteries,$18.99,No Discount,NaN,"Duracell D Alkaline Batteries, 14-count",$,Long-Lasting Batteries Designed for Dependabil...
6,Batteries,$299.99through-$449.99,Special Event - Ends on 01/21/24,NaN,Jackery Explorer 550 Portable Power Station,$,"500W Output Power, 1000W Peak High Power, La..."

The tail() method returns a specified number of last rows. The df.tail(7) in pandas returns the last 7 rows of the DataFrame df.

In [6]:
df.tail(7)

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
636,Video Games & Consoles,$34.99,No Discount,Rated 3.6 out of 5 stars based on 13 reviews.,Xbox Game Pass Core 6M Digital Download,$,Digital Download Multiplayer for Everyone ...
637,Video Games & Consoles,$629.99,No Discount,Rated 3.8 out of 5 stars based on 22 reviews.,PlayStation VR2 Horizon: Call of the Mountain ...,$,VR Headset PlayStation VR2 Sense™ Controller...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

The df.info() in pandas is used to print a concise summary of a DataFrame. This method prints information about a DataFrame including the index dtype and column dtypes, non-null values and memory usage.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643 entries, 0 to 642
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sub Category  643 non-null    object
 1   Price         642 non-null    object
 2   Discount      641 non-null    object
 3   Rating        634 non-null    object
 4   Title         643 non-null    object
 5   Currency      642 non-null    object
 6   Feature       642 non-null    object
dtypes: object(7)
memory usage: 35.3+ KB

If you use df.info without parentheses, it will return a bound method, not the actual information about the DataFrame.

In [7]:
df.info

<bound method DataFrame.info of                Sub Category     Price     Discount  \
0                 Batteries   $20.99   No Discount
1                 Batteries   $20.99   No Discount
2                 Batteries   $20.99   No Discount
3                 Batteries   $18.99   No Discount
4                 Batteries   $14.99   No Discount
..                      ...       ...          ...
638  Video Games & Consoles  $949.99   No Discount
639  Video Games & Consoles  $449.99   No Discount
640  Video Games & Consoles  $199.99   No Discount
641  Video Games & Consoles   $49.97   No Discount
642  Video Games & Consoles  $599.99   No Discount

                                             Rating  \
0                                               NaN
1                                               NaN
2                                               NaN
3                                               NaN
4    Rated 4.8 out of 5 stars based on 125 reviews.
..                                              ...
638     Rated 4 out of 5 stars based on 27 reviews.
639   Rated 3.9 out of 5 stars based on 14 reviews.
640   Rated 4.7 out of 5 stars based on 12 reviews.
641  Rated 3.9 out of 5 stars based on 180 reviews.
642   Rated 4.7 out of 5 stars based on 50 reviews.

                                                 Title Currency  \
0    Duracell Coppertop Alkaline AA Batteries, 40-c...        $
1    Duracell Coppertop Alkaline AAA Batteries, 40-...        $
2              Duracell 9V Alkaline Batteries, 8-count        $
3              Duracell C Alkaline Batteries, 14-count        $
4       Duracell 2032 Lithium Coin Batteries, 12-count        $
..                                                 ...      ...
638  Arcade1Up Infinity Game Table 32”, $100 Game C...        $
639  Arcade1Up Infinity Game Board 18.5”, $25 Game ...        $
640           Arcade1Up NBA Jam Partycade 3 Games in 1        $
641  Backbone One (Lightning) - PlayStation Edition...        $
642  Xbox Series X Diablo IV Bundle with Additional...        $

                                               Feature
0    POWER BOOST™ Ingredients   Guaranteed For 12 Y...
1    POWER BOOST™ Ingredients   Guaranteed For 12 Y...
2    Long-Lasting Batteries Designed for Dependabil...
3    Long-Lasting Batteries Designed for Dependabil...
4    Our Longest Lasting Lithium Coin Battery Ever ...
..                                                 ...
638  Tactile Feedback to add Levels of Immersion   ...
639  50 Board Games and Activities Included   18.5-...
640  3 Games Included   17-inch LCD Color Screen   ...
641  The Backbone App is Your Gaming & Streaming Hu...
642  Xbox Series X Console   Diablo® IV for Xbox On...

[643 rows x 7 columns]>

The df.isnull() in pandas is used to detect missing values in the DataFrame. It returns a DataFrame where each cell is either True or False depending on that cell's null status. True indicates a missing value and False indicates a non-missing value.

In [8]:
df.isnull()

     Sub Category  Price  Discount  Rating  Title  Currency  Feature
0           False  False     False    True  False     False    False
1           False  False     False    True  False     False    False
2           False  False     False    True  False     False    False
3           False  False     False    True  False     False    False
4           False  False     False   False  False     False    False
..            ...    ...       ...     ...    ...       ...      ...
638         False  False     False   False  False     False    False
639         False  False     False   False  False     False    False
640         False  False     False   False  False     False    False
641         False  False     False   False  False     False    False
642         False  False     False   False  False     False    False

[643 rows x 7 columns]

The df.isnull().sum() command in pandas returns the total number of missing values in each column of the DataFrame df.

In [9]:
df.isnull().sum()

Sub Category    0
Price           1
Discount        2
Rating          9
Title           0
Currency        1
Feature         1
dtype: int64

The below code calculates and prints the percentage of missing values in each column of the DataFrame df.

In [10]:
perc= df.isnull().sum()/df.shape[0] * 100
print(perc)

Sub Category    0.000000
Price           0.155521
Discount        0.311042
Rating          1.399689
Title           0.000000
Currency        0.155521
Feature         0.155521
dtype: float64

 We can use the isnull() method to create a Boolean mask and then use the sum() method to count the number of True values

In [11]:
df.isnull().sum().sum()

14

The df.dropna() function in pandas removes all rows in the DataFrame df that contain any null or missing values.

In [12]:
df.dropna()

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
8,Cameras & Camcorders,$289.99,Price valid through 1/21/24,Rated 4.2 out of 5 stars based on 238 reviews.,GoPro HERO11 Black Action Camera Bundle,$,"Also Includes: Shorty Hand Grip, Spare Enduro ..."
9,Cameras & Camcorders,$399.99,Price valid through 3/31/24,Rated 4.4 out of 5 stars based on 99 reviews.,Insta360 X3 - 5.7K 360° Action Camera Adventur...,$,X3 Captures 5.7K 360 Active HDR Video Dual 1...
10,Cameras & Camcorders,$429.99,No Discount,Rated 4.4 out of 5 stars based on 115 reviews.,DJI Mini 3 Drone Aerial Camera Bundle,$,Less Than 249g (0.55lbs) Ultralight and Foldab...
11,Cameras & Camcorders,$239.97,No Discount,Rated 4.1 out of 5 stars based on 311 reviews.,GoPro HERO10 Black Action Camera Bundle,$,"Also Includes: Extra Battery/Charger, Compact ..."
...,...,...,...,...,...,...,...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

In your code df1=df.dropna(how='any'), the how='any' means that it will drop the rows where any of the elements is missing in the DataFrame df. The resulting DataFrame df1 will not contain any rows with missing values.

In [13]:
df1=df.dropna(how='any')
print(df1)

               Sub Category     Price                     Discount  \
4                 Batteries   $14.99                   No Discount
8      Cameras & Camcorders  $289.99   Price valid through 1/21/24
9      Cameras & Camcorders  $399.99   Price valid through 3/31/24
10     Cameras & Camcorders  $429.99                   No Discount
11     Cameras & Camcorders  $239.97                   No Discount
..                      ...       ...                          ...
638  Video Games & Consoles  $949.99                   No Discount
639  Video Games & Consoles  $449.99                   No Discount
640  Video Games & Consoles  $199.99                   No Discount
641  Video Games & Consoles   $49.97                   No Discount
642  Video Games & Consoles  $599.99                   No Discount

                                             Rating  \
4    Rated 4.8 out of 5 stars based on 125 reviews.
8    Rated 4.2 out of 5 stars based on 238 reviews.
9     Rated 4.4 out of 5 stars based on 99 reviews.
10   Rated 4.4 out of 5 stars based on 115 reviews.
11   Rated 4.1 out of 5 stars based on 311 reviews.
..                                              ...
638     Rated 4 out of 5 stars based on 27 reviews.
639   Rated 3.9 out of 5 stars based on 14 reviews.
640   Rated 4.7 out of 5 stars based on 12 reviews.
641  Rated 3.9 out of 5 stars based on 180 reviews.
642   Rated 4.7 out of 5 stars based on 50 reviews.

                                                 Title Currency  \
4       Duracell 2032 Lithium Coin Batteries, 12-count        $
8              GoPro HERO11 Black Action Camera Bundle        $
9    Insta360 X3 - 5.7K 360° Action Camera Adventur...        $
10               DJI Mini 3 Drone Aerial Camera Bundle        $
11             GoPro HERO10 Black Action Camera Bundle        $
..                                                 ...      ...
638  Arcade1Up Infinity Game Table 32”, $100 Game C...        $
639  Arcade1Up Infinity Game Board 18.5”, $25 Game ...        $
640           Arcade1Up NBA Jam Partycade 3 Games in 1        $
641  Backbone One (Lightning) - PlayStation Edition...        $
642  Xbox Series X Diablo IV Bundle with Additional...        $

                                               Feature
4    Our Longest Lasting Lithium Coin Battery Ever ...
8    Also Includes: Shorty Hand Grip, Spare Enduro ...
9    X3 Captures 5.7K 360 Active HDR Video   Dual 1...
10   Less Than 249g (0.55lbs) Ultralight and Foldab...
11   Also Includes: Extra Battery/Charger, Compact ...
..                                                 ...
638  Tactile Feedback to add Levels of Immersion   ...
639  50 Board Games and Activities Included   18.5-...
640  3 Games Included   17-inch LCD Color Screen   ...
641  The Backbone App is Your Gaming & Streaming Hu...
642  Xbox Series X Console   Diablo® IV for Xbox On...

[632 rows x 7 columns]

The code dff=df.dropna(how='all') removes the rows in the DataFrame df where all elements are missing or null. The resulting DataFrame is then assigned to dff. The print(dff) statement displays the contents of dff.

In [14]:
dff=df.dropna(how='all')
print(dff)

               Sub Category     Price     Discount  \
0                 Batteries   $20.99   No Discount
1                 Batteries   $20.99   No Discount
2                 Batteries   $20.99   No Discount
3                 Batteries   $18.99   No Discount
4                 Batteries   $14.99   No Discount
..                      ...       ...          ...
638  Video Games & Consoles  $949.99   No Discount
639  Video Games & Consoles  $449.99   No Discount
640  Video Games & Consoles  $199.99   No Discount
641  Video Games & Consoles   $49.97   No Discount
642  Video Games & Consoles  $599.99   No Discount

                                             Rating  \
0                                               NaN
1                                               NaN
2                                               NaN
3                                               NaN
4    Rated 4.8 out of 5 stars based on 125 reviews.
..                                              ...
638     Rated 4 out of 5 stars based on 27 reviews.
639   Rated 3.9 out of 5 stars based on 14 reviews.
640   Rated 4.7 out of 5 stars based on 12 reviews.
641  Rated 3.9 out of 5 stars based on 180 reviews.
642   Rated 4.7 out of 5 stars based on 50 reviews.

                                                 Title Currency  \
0    Duracell Coppertop Alkaline AA Batteries, 40-c...        $
1    Duracell Coppertop Alkaline AAA Batteries, 40-...        $
2              Duracell 9V Alkaline Batteries, 8-count        $
3              Duracell C Alkaline Batteries, 14-count        $
4       Duracell 2032 Lithium Coin Batteries, 12-count        $
..                                                 ...      ...
638  Arcade1Up Infinity Game Table 32”, $100 Game C...        $
639  Arcade1Up Infinity Game Board 18.5”, $25 Game ...        $
640           Arcade1Up NBA Jam Partycade 3 Games in 1        $
641  Backbone One (Lightning) - PlayStation Edition...        $
642  Xbox Series X Diablo IV Bundle with Additional...        $

                                               Feature
0    POWER BOOST™ Ingredients   Guaranteed For 12 Y...
1    POWER BOOST™ Ingredients   Guaranteed For 12 Y...
2    Long-Lasting Batteries Designed for Dependabil...
3    Long-Lasting Batteries Designed for Dependabil...
4    Our Longest Lasting Lithium Coin Battery Ever ...
..                                                 ...
638  Tactile Feedback to add Levels of Immersion   ...
639  50 Board Games and Activities Included   18.5-...
640  3 Games Included   17-inch LCD Color Screen   ...
641  The Backbone App is Your Gaming & Streaming Hu...
642  Xbox Series X Console   Diablo® IV for Xbox On...

[643 rows x 7 columns]

In [15]:
df1.shape

(632, 7)

In [16]:
dff.shape

(643, 7)

In [17]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 632 entries, 4 to 642
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sub Category  632 non-null    object
 1   Price         632 non-null    object
 2   Discount      632 non-null    object
 3   Rating        632 non-null    object
 4   Title         632 non-null    object
 5   Currency      632 non-null    object
 6   Feature       632 non-null    object
dtypes: object(7)
memory usage: 39.5+ KB

In [18]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643 entries, 0 to 642
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sub Category  643 non-null    object
 1   Price         642 non-null    object
 2   Discount      641 non-null    object
 3   Rating        634 non-null    object
 4   Title         643 non-null    object
 5   Currency      642 non-null    object
 6   Feature       642 non-null    object
dtypes: object(7)
memory usage: 35.3+ KB

The dropna() method removes the rows that contains NULL values

The df.dropna(axis=0) function in pandas removes all rows (since axis=0 refers to rows) in the DataFrame df that contain any null or missing values

In [19]:
df.dropna(axis=0)

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
8,Cameras & Camcorders,$289.99,Price valid through 1/21/24,Rated 4.2 out of 5 stars based on 238 reviews.,GoPro HERO11 Black Action Camera Bundle,$,"Also Includes: Shorty Hand Grip, Spare Enduro ..."
9,Cameras & Camcorders,$399.99,Price valid through 3/31/24,Rated 4.4 out of 5 stars based on 99 reviews.,Insta360 X3 - 5.7K 360° Action Camera Adventur...,$,X3 Captures 5.7K 360 Active HDR Video Dual 1...
10,Cameras & Camcorders,$429.99,No Discount,Rated 4.4 out of 5 stars based on 115 reviews.,DJI Mini 3 Drone Aerial Camera Bundle,$,Less Than 249g (0.55lbs) Ultralight and Foldab...
11,Cameras & Camcorders,$239.97,No Discount,Rated 4.1 out of 5 stars based on 311 reviews.,GoPro HERO10 Black Action Camera Bundle,$,"Also Includes: Extra Battery/Charger, Compact ..."
...,...,...,...,...,...,...,...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

The df.dropna(axis=1) function in pandas removes all columns (since axis=1 refers to columns) in the DataFrame df that contain any null or missing values

In [20]:
df.dropna(axis=1)

               Sub Category                                              Title
0                 Batteries  Duracell Coppertop Alkaline AA Batteries, 40-c...
1                 Batteries  Duracell Coppertop Alkaline AAA Batteries, 40-...
2                 Batteries            Duracell 9V Alkaline Batteries, 8-count
3                 Batteries            Duracell C Alkaline Batteries, 14-count
4                 Batteries     Duracell 2032 Lithium Coin Batteries, 12-count
..                      ...                                                ...
638  Video Games & Consoles  Arcade1Up Infinity Game Table 32”, $100 Game C...
639  Video Games & Consoles  Arcade1Up Infinity Game Board 18.5”, $25 Game ...
640  Video Games & Consoles           Arcade1Up NBA Jam Partycade 3 Games in 1
641  Video Games & Consoles  Backbone One (Lightning) - PlayStation Edition...
642  Video Games & Consoles  Xbox Series X Diablo IV Bundle with Additional...

[643 rows x 2 columns]

In [21]:
df.dropna()

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
8,Cameras & Camcorders,$289.99,Price valid through 1/21/24,Rated 4.2 out of 5 stars based on 238 reviews.,GoPro HERO11 Black Action Camera Bundle,$,"Also Includes: Shorty Hand Grip, Spare Enduro ..."
9,Cameras & Camcorders,$399.99,Price valid through 3/31/24,Rated 4.4 out of 5 stars based on 99 reviews.,Insta360 X3 - 5.7K 360° Action Camera Adventur...,$,X3 Captures 5.7K 360 Active HDR Video Dual 1...
10,Cameras & Camcorders,$429.99,No Discount,Rated 4.4 out of 5 stars based on 115 reviews.,DJI Mini 3 Drone Aerial Camera Bundle,$,Less Than 249g (0.55lbs) Ultralight and Foldab...
11,Cameras & Camcorders,$239.97,No Discount,Rated 4.1 out of 5 stars based on 311 reviews.,GoPro HERO10 Black Action Camera Bundle,$,"Also Includes: Extra Battery/Charger, Compact ..."
...,...,...,...,...,...,...,...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

The df.dropna(subset='Rating') function in pandas removes all rows in the DataFrame df where the 'Rating' column has null or missing values. The subset parameter is used to specify the columns where we check for missing values.

In [22]:
df.dropna(subset='Rating')

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
8,Cameras & Camcorders,$289.99,Price valid through 1/21/24,Rated 4.2 out of 5 stars based on 238 reviews.,GoPro HERO11 Black Action Camera Bundle,$,"Also Includes: Shorty Hand Grip, Spare Enduro ..."
9,Cameras & Camcorders,$399.99,Price valid through 3/31/24,Rated 4.4 out of 5 stars based on 99 reviews.,Insta360 X3 - 5.7K 360° Action Camera Adventur...,$,X3 Captures 5.7K 360 Active HDR Video Dual 1...
10,Cameras & Camcorders,$429.99,No Discount,Rated 4.4 out of 5 stars based on 115 reviews.,DJI Mini 3 Drone Aerial Camera Bundle,$,Less Than 249g (0.55lbs) Ultralight and Foldab...
11,Cameras & Camcorders,$239.97,No Discount,Rated 4.1 out of 5 stars based on 311 reviews.,GoPro HERO10 Black Action Camera Bundle,$,"Also Includes: Extra Battery/Charger, Compact ..."
...,...,...,...,...,...,...,...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

The df.dropna(subset= ['Rating','Price','Discount','Currency','Feature']) function in pandas removes all rows in the DataFrame df where any of the specified columns ('Rating', 'Price', 'Discount', 'Currency', 'Feature') have null or missing values.

In [23]:
df.dropna(subset= ['Rating','Price','Discount','Currency','Feature'])

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
8,Cameras & Camcorders,$289.99,Price valid through 1/21/24,Rated 4.2 out of 5 stars based on 238 reviews.,GoPro HERO11 Black Action Camera Bundle,$,"Also Includes: Shorty Hand Grip, Spare Enduro ..."
9,Cameras & Camcorders,$399.99,Price valid through 3/31/24,Rated 4.4 out of 5 stars based on 99 reviews.,Insta360 X3 - 5.7K 360° Action Camera Adventur...,$,X3 Captures 5.7K 360 Active HDR Video Dual 1...
10,Cameras & Camcorders,$429.99,No Discount,Rated 4.4 out of 5 stars based on 115 reviews.,DJI Mini 3 Drone Aerial Camera Bundle,$,Less Than 249g (0.55lbs) Ultralight and Foldab...
11,Cameras & Camcorders,$239.97,No Discount,Rated 4.1 out of 5 stars based on 311 reviews.,GoPro HERO10 Black Action Camera Bundle,$,"Also Includes: Extra Battery/Charger, Compact ..."
...,...,...,...,...,...,...,...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

The df.dropna(subset= ['Rating','Price','Discount']) function in pandas removes all rows in the DataFrame df where any of the specified columns ('Rating', 'Price', 'Discount', 'Currency', 'Feature') have null or missing values.

In [24]:
df.dropna(subset= ['Rating','Price','Discount'])

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
8,Cameras & Camcorders,$289.99,Price valid through 1/21/24,Rated 4.2 out of 5 stars based on 238 reviews.,GoPro HERO11 Black Action Camera Bundle,$,"Also Includes: Shorty Hand Grip, Spare Enduro ..."
9,Cameras & Camcorders,$399.99,Price valid through 3/31/24,Rated 4.4 out of 5 stars based on 99 reviews.,Insta360 X3 - 5.7K 360° Action Camera Adventur...,$,X3 Captures 5.7K 360 Active HDR Video Dual 1...
10,Cameras & Camcorders,$429.99,No Discount,Rated 4.4 out of 5 stars based on 115 reviews.,DJI Mini 3 Drone Aerial Camera Bundle,$,Less Than 249g (0.55lbs) Ultralight and Foldab...
11,Cameras & Camcorders,$239.97,No Discount,Rated 4.1 out of 5 stars based on 311 reviews.,GoPro HERO10 Black Action Camera Bundle,$,"Also Includes: Extra Battery/Charger, Compact ..."
...,...,...,...,...,...,...,...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

The df.dropna(thresh=2) function in pandas removes all rows in the DataFrame df that have less than 2 non-null values. The thresh parameter is used to specify the minimum number of non-null values a row must have to avoid being dropped.

In [25]:
df.dropna(thresh=2)

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
0,Batteries,$20.99,No Discount,NaN,"Duracell Coppertop Alkaline AA Batteries, 40-c...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
1,Batteries,$20.99,No Discount,NaN,"Duracell Coppertop Alkaline AAA Batteries, 40-...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
2,Batteries,$20.99,No Discount,NaN,"Duracell 9V Alkaline Batteries, 8-count",$,Long-Lasting Batteries Designed for Dependabil...
3,Batteries,$18.99,No Discount,NaN,"Duracell C Alkaline Batteries, 14-count",$,Long-Lasting Batteries Designed for Dependabil...
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
...,...,...,...,...,...,...,...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

The df.dropna(thresh=5) function in pandas removes all rows in the DataFrame df that have less than 5 non-null values. The thresh parameter is used to specify the minimum number of non-null values a row must have to avoid being dropped.

In [26]:
df.dropna(thresh=5)

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
0,Batteries,$20.99,No Discount,NaN,"Duracell Coppertop Alkaline AA Batteries, 40-c...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
1,Batteries,$20.99,No Discount,NaN,"Duracell Coppertop Alkaline AAA Batteries, 40-...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
2,Batteries,$20.99,No Discount,NaN,"Duracell 9V Alkaline Batteries, 8-count",$,Long-Lasting Batteries Designed for Dependabil...
3,Batteries,$18.99,No Discount,NaN,"Duracell C Alkaline Batteries, 14-count",$,Long-Lasting Batteries Designed for Dependabil...
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
...,...,...,...,...,...,...,...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

The df.dropna(thresh=7) function in pandas removes all rows in the DataFrame df that have less than 7 non-null values. The thresh parameter is used to specify the minimum number of non-null values a row must have to avoid being dropped.

In [27]:
df.dropna(thresh=7)

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
8,Cameras & Camcorders,$289.99,Price valid through 1/21/24,Rated 4.2 out of 5 stars based on 238 reviews.,GoPro HERO11 Black Action Camera Bundle,$,"Also Includes: Shorty Hand Grip, Spare Enduro ..."
9,Cameras & Camcorders,$399.99,Price valid through 3/31/24,Rated 4.4 out of 5 stars based on 99 reviews.,Insta360 X3 - 5.7K 360° Action Camera Adventur...,$,X3 Captures 5.7K 360 Active HDR Video Dual 1...
10,Cameras & Camcorders,$429.99,No Discount,Rated 4.4 out of 5 stars based on 115 reviews.,DJI Mini 3 Drone Aerial Camera Bundle,$,Less Than 249g (0.55lbs) Ultralight and Foldab...
11,Cameras & Camcorders,$239.97,No Discount,Rated 4.1 out of 5 stars based on 311 reviews.,GoPro HERO10 Black Action Camera Bundle,$,"Also Includes: Extra Battery/Charger, Compact ..."
...,...,...,...,...,...,...,...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

In [28]:
df.isnull().sum()

Sub Category    0
Price           1
Discount        2
Rating          9
Title           0
Currency        1
Feature         1
dtype: int64

In [29]:
df.info

<bound method DataFrame.info of                Sub Category     Price     Discount  \
0                 Batteries   $20.99   No Discount
1                 Batteries   $20.99   No Discount
2                 Batteries   $20.99   No Discount
3                 Batteries   $18.99   No Discount
4                 Batteries   $14.99   No Discount
..                      ...       ...          ...
638  Video Games & Consoles  $949.99   No Discount
639  Video Games & Consoles  $449.99   No Discount
640  Video Games & Consoles  $199.99   No Discount
641  Video Games & Consoles   $49.97   No Discount
642  Video Games & Consoles  $599.99   No Discount

                                             Rating  \
0                                               NaN
1                                               NaN
2                                               NaN
3                                               NaN
4    Rated 4.8 out of 5 stars based on 125 reviews.
..                                              ...
638     Rated 4 out of 5 stars based on 27 reviews.
639   Rated 3.9 out of 5 stars based on 14 reviews.
640   Rated 4.7 out of 5 stars based on 12 reviews.
641  Rated 3.9 out of 5 stars based on 180 reviews.
642   Rated 4.7 out of 5 stars based on 50 reviews.

                                                 Title Currency  \
0    Duracell Coppertop Alkaline AA Batteries, 40-c...        $
1    Duracell Coppertop Alkaline AAA Batteries, 40-...        $
2              Duracell 9V Alkaline Batteries, 8-count        $
3              Duracell C Alkaline Batteries, 14-count        $
4       Duracell 2032 Lithium Coin Batteries, 12-count        $
..                                                 ...      ...
638  Arcade1Up Infinity Game Table 32”, $100 Game C...        $
639  Arcade1Up Infinity Game Board 18.5”, $25 Game ...        $
640           Arcade1Up NBA Jam Partycade 3 Games in 1        $
641  Backbone One (Lightning) - PlayStation Edition...        $
642  Xbox Series X Diablo IV Bundle with Additional...        $

                                               Feature
0    POWER BOOST™ Ingredients   Guaranteed For 12 Y...
1    POWER BOOST™ Ingredients   Guaranteed For 12 Y...
2    Long-Lasting Batteries Designed for Dependabil...
3    Long-Lasting Batteries Designed for Dependabil...
4    Our Longest Lasting Lithium Coin Battery Ever ...
..                                                 ...
638  Tactile Feedback to add Levels of Immersion   ...
639  50 Board Games and Activities Included   18.5-...
640  3 Games Included   17-inch LCD Color Screen   ...
641  The Backbone App is Your Gaming & Streaming Hu...
642  Xbox Series X Console   Diablo® IV for Xbox On...

[643 rows x 7 columns]>

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643 entries, 0 to 642
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sub Category  643 non-null    object
 1   Price         642 non-null    object
 2   Discount      641 non-null    object
 3   Rating        634 non-null    object
 4   Title         643 non-null    object
 5   Currency      642 non-null    object
 6   Feature       642 non-null    object
dtypes: object(7)
memory usage: 35.3+ KB

In [31]:
df.head()

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
0,Batteries,$20.99,No Discount,NaN,"Duracell Coppertop Alkaline AA Batteries, 40-c...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
1,Batteries,$20.99,No Discount,NaN,"Duracell Coppertop Alkaline AAA Batteries, 40-...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
2,Batteries,$20.99,No Discount,NaN,"Duracell 9V Alkaline Batteries, 8-count",$,Long-Lasting Batteries Designed for Dependabil...
3,Batteries,$18.99,No Discount,NaN,"Duracell C Alkaline Batteries, 14-count",$,Long-Lasting Batteries Designed for Dependabil...
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...

The code df1 = df.fillna(value=values) in pandas replaces all null or missing values in the DataFrame df with the corresponding values specified in the values dictionary, and assigns the resulting DataFrame to df1.

In [32]:
values={'Price': '$20','Discount': 'some values','Rating': '3 star','Currency' : 'INR', 'Features' : 'short'}
df1 = df.fillna(value=values)
df1

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
0,Batteries,$20.99,No Discount,3 star,"Duracell Coppertop Alkaline AA Batteries, 40-c...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
1,Batteries,$20.99,No Discount,3 star,"Duracell Coppertop Alkaline AAA Batteries, 40-...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
2,Batteries,$20.99,No Discount,3 star,"Duracell 9V Alkaline Batteries, 8-count",$,Long-Lasting Batteries Designed for Dependabil...
3,Batteries,$18.99,No Discount,3 star,"Duracell C Alkaline Batteries, 14-count",$,Long-Lasting Batteries Designed for Dependabil...
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
...,...,...,...,...,...,...,...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

The ffill1= df.fillna(method = "ffill") line of code in pandas fills the null or missing values in the DataFrame df with the value of the previous row (forward fill). The resulting DataFrame is then assigned to ffill1. This is particularly useful in time series data where you might want to fill missing values with the last known value.

In [33]:
ffill1= df.fillna(method = "ffill")
ffill1

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
0,Batteries,$20.99,No Discount,NaN,"Duracell Coppertop Alkaline AA Batteries, 40-c...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
1,Batteries,$20.99,No Discount,NaN,"Duracell Coppertop Alkaline AAA Batteries, 40-...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
2,Batteries,$20.99,No Discount,NaN,"Duracell 9V Alkaline Batteries, 8-count",$,Long-Lasting Batteries Designed for Dependabil...
3,Batteries,$18.99,No Discount,NaN,"Duracell C Alkaline Batteries, 14-count",$,Long-Lasting Batteries Designed for Dependabil...
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
...,...,...,...,...,...,...,...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

The bfill1= df.fillna(method = "bfill") line of code in pandas fills the null or missing values in the DataFrame df with the value of the next row (backward fill). The resulting DataFrame is then assigned to bfill1. This is particularly useful in time series data where you might want to fill missing values with the next known value.

In [34]:
bfill1= df.fillna(method = "bfill")
bfill1

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
0,Batteries,$20.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell Coppertop Alkaline AA Batteries, 40-c...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
1,Batteries,$20.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell Coppertop Alkaline AAA Batteries, 40-...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
2,Batteries,$20.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 9V Alkaline Batteries, 8-count",$,Long-Lasting Batteries Designed for Dependabil...
3,Batteries,$18.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell C Alkaline Batteries, 14-count",$,Long-Lasting Batteries Designed for Dependabil...
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
...,...,...,...,...,...,...,...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

The code df1 = df.fillna(value=values, limit = 2) in pandas replaces the first two null or missing values in each column of the DataFrame df with the corresponding values specified in the values dictionary. The resulting DataFrame is then assigned to df1.  

The limit=2 parameter is used to restrict the operation to the first two missing values in each column. This means that if a column has more than two missing values, only the first two will be replaced, and the rest will remain as missing values. This can be useful when you want to fill in missing values but maintain some level of missing data for analysis.

In [35]:
values={'Price': '$20','Discount': 'some values','Rating': '3 star','Currency' : 'INR', 'Features' : 'short'}
df1 = df.fillna(value=values, limit = 2)
df1

,Sub Category,Price,Discount,Rating,Title,Currency,Feature
0,Batteries,$20.99,No Discount,3 star,"Duracell Coppertop Alkaline AA Batteries, 40-c...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
1,Batteries,$20.99,No Discount,3 star,"Duracell Coppertop Alkaline AAA Batteries, 40-...",$,POWER BOOST™ Ingredients Guaranteed For 12 Y...
2,Batteries,$20.99,No Discount,NaN,"Duracell 9V Alkaline Batteries, 8-count",$,Long-Lasting Batteries Designed for Dependabil...
3,Batteries,$18.99,No Discount,NaN,"Duracell C Alkaline Batteries, 14-count",$,Long-Lasting Batteries Designed for Dependabil...
4,Batteries,$14.99,No Discount,Rated 4.8 out of 5 stars based on 125 reviews.,"Duracell 2032 Lithium Coin Batteries, 12-count",$,Our Longest Lasting Lithium Coin Battery Ever ...
...,...,...,...,...,...,...,...
638,Video Games & Consoles,$949.99,No Discount,Rated 4 out of 5 stars based on 27 reviews.,"Arcade1Up Infinity Game Table 32”, $100 Game C...",$,Tactile Feedback to add Levels of Immersion ...
639,Video Games & Consoles,$449.99,No Discount,Rated 3.9 out of 5 stars based on 14 reviews.,"Arcade1Up Infinity Game Board 18.5”, $25 Game ...",$,50 Board Games and Activities Included 18.5-...
640,Video Games & Consoles,$199.99,No Discount,Rated 4.7 out of 5 stars based on 12 reviews.,Arcade1Up NBA Jam Partycade 3 Games in 1,$,3 Games Included 17-inch LCD Color Screen ...
641,Video Games & Consoles,$49.97,No Discount,Rated 3.9 out of 5 stars based on 180 reviews.,Backbone One (Lightning) - PlayStation Edition...,$,The Backbone App is Your Gaming & Streaming Hu...
642,Video Games & Consoles,$599.99,No Discount,Rated 4.7 out of 5 stars based on 50 reviews.,Xbox Series X Diablo IV Bundle with Additional...,$,Xbox Series X Console Diablo® IV for Xbox On...

In [36]:
df1.isnull().sum()

Sub Category    0
Price           0
Discount        0
Rating          7
Title           0
Currency        0
Feature         1
dtype: int64