# Aim : Missing values imputation.

**Name : Trideep Nandi**

**Class : CS4**

**Batch: 2**

**Enrollment : 0827CS211248**

This experiment deals with the splitting of the dataset into numeric and categorical data

Importing Necessary Libraries

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

 "SimpleImputer" is a sci-kit library used to fill in the missing values in the datasets

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
df=pd.read_csv('/content/cars_ds_final.csv')

info gives general information about the dataset like number of records , columns , memory usage or size of dataset.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Columns: 141 entries, Unnamed: 0 to Electric_Range
dtypes: float64(6), int64(1), object(134)
memory usage: 1.4+ MB

null values are added using isnull().sum() command and displayed for each column.

In [ ]:
df.isnull().sum()

Unnamed: 0              0
Make                   75
Model                   0
Variant                 0
Ex-Showroom_Price       0
                     ...
USB_Ports            1247
Heads-Up_Display     1225
Welcome_Lights       1207
Battery              1263
Electric_Range       1259
Length: 141, dtype: int64

The include parameter when set to float and int64 will create  only numeric data frame

In [ ]:
num_var= df.select_dtypes(include =["float","int64"])
num_var.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1276 non-null   int64
 1   Cylinders            1210 non-null   float64
 2   Valves_Per_Cylinder  1174 non-null   float64
 3   Doors                1272 non-null   float64
 4   Seating_Capacity     1270 non-null   float64
 5   Number_of_Airbags    1141 non-null   float64
 6   USB_Ports            29 non-null     float64
dtypes: float64(6), int64(1)
memory usage: 69.9 KB

  Here as the include parameter is set to 0 , so it will  create  only categorical data frame with all the categorical records .

In [ ]:
num_var1= df.select_dtypes(include =["O"])
num_var1

,Make,Model,Variant,Ex-Showroom_Price,Displacement,Drivetrain,Cylinder_Configuration,Emission_Norm,Engine_Location,Fuel_System,...,Paddle_Shifters,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,RWD (Rear Wheel Drive),In-line,BS IV,"Rear, Transverse",Injection,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,RWD (Rear Wheel Drive),In-line,BS IV,"Rear, Transverse",Injection,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,RWD (Rear Wheel Drive),In-line,BS IV,"Rear, Transverse",Injection,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,RWD (Rear Wheel Drive),In-line,BS IV,"Rear, Transverse",Injection,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,RWD (Rear Wheel Drive),In-line,BS IV,"Rear, Transverse",Injection,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1271,Honda,City,Vx Mt Diesel,"Rs. 13,02,000",1498 cc,FWD (Front Wheel Drive),In-line,BS IV,"Front, Transverse",Injection,...,NaN,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN
1272,Honda,City,Zx Mt Diesel,"Rs. 14,21,000",1498 cc,FWD (Front Wheel Drive),In-line,BS IV,"Front, Transverse",Injection,...,NaN,Yes,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN
1273,Honda,City,Zx Cvt Petrol,"Rs. 14,31,000",1497 cc,FWD (Front Wheel Drive),In-line,BS 6,"Front, Transverse",Injection,...,Yes,Yes,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN
1274,Honda,City,V Cvt Petrol,"Rs. 12,01,000",1497 cc,FWD (Front Wheel Drive),In-line,BS 6,"Front, Transverse",Injection,...,Yes,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN
1275,Mitsubishi,Montero,3.2 At,"Rs. 68,62,560",3200 cc,AWD (All Wheel Drive),In-line,BS IV,"Front, Longitudinal",Injection,...,NaN,Yes,NaN,NaN,Yes,Yes,NaN,NaN,NaN,NaN